// <auto-generated />
using System;
using KakaoExpenseClaim.ClaimManagement.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KakaoExpenseClaim.ClaimManagement.Persistence.Migrations
{
    [DbContext(typeof(ExpenseClaimDbContext))]
    partial class ExpenseClaimDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KakaoExpenseClaim.ClaimManagement.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "RO",
                            Name = "Rent Office"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HO",
                            Name = "Home office costs"
                        },
                        new
                        {
                            Id = 3,
                            Code = "UT",
                            Name = "Utilities"
                        },
                        new
                        {
                            Id = 4,
                            Code = "FUR",
                            Name = "Furniture"
                        },
                        new
                        {
                            Id = 5,
                            Code = "SPP",
                            Name = "Office supplies"
                        },
                        new
                        {
                            Id = 6,
                            Code = "EQ",
                            Name = "Equipment"
                        },
                        new
                        {
                            Id = 7,
                            Code = "MC",
                            Name = "Machinery"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AM",
                            Name = "Advertising and marketing"
                        },
                        new
                        {
                            Id = 9,
                            Code = "WS",
                            Name = "Website and software expenses"
                        },
                        new
                        {
                            Id = 10,
                            Code = "ET",
                            Name = "Entertainment"
                        });
                });

            modelBuilder.Entity("KakaoExpenseClaim.ClaimManagement.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "EUR",
                            Symbol = "€"
                        },
                        new
                        {
                            Id = 2,
                            Name = "KRW",
                            Symbol = "₩"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CAD",
                            Symbol = "C$"
                        },
                        new
                        {
                            Id = 4,
                            Name = "JPN",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = 5,
                            Name = "USD",
                            Symbol = "$"
                        });
                });

            modelBuilder.Entity("KakaoExpenseClaim.ClaimManagement.Domain.Entities.ExpenseClaim", b =>
                {
                    b.Property<int>("ExpenseClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApproverComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApproverId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinanceComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FinanceId")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RequesterComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequesterId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ExpenseClaimId");

                    b.ToTable("ExpenseClaims");

                    b.HasData(
                        new
                        {
                            ExpenseClaimId = 1,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000986,
                            Status = 1,
                            SubmitDate = new DateTime(2021, 11, 15, 22, 56, 33, 423, DateTimeKind.Local).AddTicks(1898),
                            Title = "Expense Claim case 1",
                            TotalAmount = 60915m
                        },
                        new
                        {
                            ExpenseClaimId = 2,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000986,
                            Status = 1,
                            SubmitDate = new DateTime(2021, 11, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7409),
                            Title = "Expense Claim case 2",
                            TotalAmount = 27098m
                        },
                        new
                        {
                            ExpenseClaimId = 3,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000986,
                            Status = 1,
                            SubmitDate = new DateTime(2021, 11, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7529),
                            Title = "Expense Claim case 3",
                            TotalAmount = 60227m
                        },
                        new
                        {
                            ExpenseClaimId = 4,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000986,
                            Status = 1,
                            SubmitDate = new DateTime(2021, 11, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7557),
                            Title = "Expense Claim case 4",
                            TotalAmount = 5840m
                        },
                        new
                        {
                            ExpenseClaimId = 5,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000986,
                            Status = 1,
                            SubmitDate = new DateTime(2021, 8, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7575),
                            Title = "Expense Claim case 5",
                            TotalAmount = 16434m
                        },
                        new
                        {
                            ExpenseClaimId = 6,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000986,
                            Status = 5,
                            SubmitDate = new DateTime(2021, 8, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7600),
                            Title = "Expense Claim case 6",
                            TotalAmount = 63415m
                        },
                        new
                        {
                            ExpenseClaimId = 7,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000319,
                            Status = 5,
                            SubmitDate = new DateTime(2021, 5, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7617),
                            Title = "Expense Claim case 7",
                            TotalAmount = 77098m
                        },
                        new
                        {
                            ExpenseClaimId = 8,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000812,
                            Status = 5,
                            SubmitDate = new DateTime(2021, 5, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7634),
                            Title = "Expense Claim case 8",
                            TotalAmount = 10227m
                        },
                        new
                        {
                            ExpenseClaimId = 9,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000546,
                            Status = 5,
                            SubmitDate = new DateTime(2021, 11, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7652),
                            Title = "Expense Claim case 9",
                            TotalAmount = 3840m
                        },
                        new
                        {
                            ExpenseClaimId = 10,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000173,
                            Status = 5,
                            SubmitDate = new DateTime(2021, 5, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7671),
                            Title = "Expense Claim case 10",
                            TotalAmount = 76434m
                        },
                        new
                        {
                            ExpenseClaimId = 11,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000986,
                            Status = 5,
                            SubmitDate = new DateTime(2021, 5, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7688),
                            Title = "Expense Claim case 11",
                            TotalAmount = 50915m
                        },
                        new
                        {
                            ExpenseClaimId = 12,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000319,
                            Status = 1,
                            SubmitDate = new DateTime(2021, 8, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7705),
                            Title = "Expense Claim case 12",
                            TotalAmount = 97098m
                        },
                        new
                        {
                            ExpenseClaimId = 13,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000812,
                            Status = 1,
                            SubmitDate = new DateTime(2021, 8, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7722),
                            Title = "Expense Claim case 13",
                            TotalAmount = 80227m
                        },
                        new
                        {
                            ExpenseClaimId = 14,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000546,
                            Status = 1,
                            SubmitDate = new DateTime(2021, 5, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7739),
                            Title = "Expense Claim case 14",
                            TotalAmount = 4840m
                        },
                        new
                        {
                            ExpenseClaimId = 15,
                            ApprovalDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ApproverId = 0,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinanceId = 0,
                            ProcessedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequesterComments = "please, check this out and approve it	",
                            RequesterId = 21000173,
                            Status = 1,
                            SubmitDate = new DateTime(2021, 5, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(7756),
                            Title = "Expense Claim case 15",
                            TotalAmount = 26434m
                        });
                });

            modelBuilder.Entity("KakaoExpenseClaim.ClaimManagement.Domain.Entities.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExpenseClaimId")
                        .HasColumnType("int");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PayeeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Receipt")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal>("USDAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId");

                    b.HasIndex("ExpenseClaimId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Amount = 240m,
                            CategoryId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 1,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 429, DateTimeKind.Local).AddTicks(9918),
                            Description = "	Home office costs, Feb 2020	",
                            ExpenseClaimId = 5,
                            PayeeId = 21000986,
                            USDAmount = 290m
                        },
                        new
                        {
                            ItemId = 2,
                            Amount = 50000m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 2,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(3729),
                            Description = "	Utilities, Jan 2019	",
                            ExpenseClaimId = 1,
                            PayeeId = 21000365,
                            USDAmount = 45m
                        },
                        new
                        {
                            ItemId = 3,
                            Amount = 240m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 3,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(3791),
                            Description = "	Furniture, March 2020	",
                            ExpenseClaimId = 3,
                            PayeeId = 21000173,
                            USDAmount = 197m
                        },
                        new
                        {
                            ItemId = 4,
                            Amount = 20000m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 4,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(3855),
                            Description = "	Advertising and marketing, Feb 2020	",
                            ExpenseClaimId = 4,
                            PayeeId = 21000546,
                            USDAmount = 182m
                        },
                        new
                        {
                            ItemId = 5,
                            Amount = 5567m,
                            CategoryId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 5,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(3880),
                            Description = "	Entertainment, Oct 2018	",
                            ExpenseClaimId = 2,
                            PayeeId = 21000812,
                            USDAmount = 5567m
                        },
                        new
                        {
                            ItemId = 6,
                            Amount = 645m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 1,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(3905),
                            Description = "	Website and software expenses, Nov 2021	",
                            ExpenseClaimId = 5,
                            PayeeId = 21000319,
                            USDAmount = 780m
                        },
                        new
                        {
                            ItemId = 7,
                            Amount = 770000m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 2,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(3925),
                            Description = "	Office supplies, Sept 2019	",
                            ExpenseClaimId = 1,
                            PayeeId = 21000986,
                            USDAmount = 685m
                        },
                        new
                        {
                            ItemId = 8,
                            Amount = 5356m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 3,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(3945),
                            Description = "	Office supplies, Sept 2019	",
                            ExpenseClaimId = 3,
                            PayeeId = 21000365,
                            USDAmount = 4392m
                        },
                        new
                        {
                            ItemId = 9,
                            Amount = 105070m,
                            CategoryId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 4,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(3964),
                            Description = "	Entertainment, Oct 2018	",
                            ExpenseClaimId = 4,
                            PayeeId = 21000173,
                            USDAmount = 956m
                        },
                        new
                        {
                            ItemId = 10,
                            Amount = 3860m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 5,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(3984),
                            Description = "	Utilities, Jan 2019	",
                            ExpenseClaimId = 2,
                            PayeeId = 21000546,
                            USDAmount = 3860m
                        },
                        new
                        {
                            ItemId = 11,
                            Amount = 4435m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 1,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4002),
                            Description = "	Office supplies, May 2021	",
                            ExpenseClaimId = 5,
                            PayeeId = 21000812,
                            USDAmount = 5366m
                        },
                        new
                        {
                            ItemId = 12,
                            Amount = 450000m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 2,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4021),
                            Description = "	Office supplies, Sept 2019	",
                            ExpenseClaimId = 1,
                            PayeeId = 21000319,
                            USDAmount = 401m
                        },
                        new
                        {
                            ItemId = 13,
                            Amount = 5446m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 3,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4042),
                            Description = "	Advertising and marketing, Feb 2020	",
                            ExpenseClaimId = 3,
                            PayeeId = 21000986,
                            USDAmount = 4466m
                        },
                        new
                        {
                            ItemId = 14,
                            Amount = 38740m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 4,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4074),
                            Description = "	Advertising and marketing, Feb 2020	",
                            ExpenseClaimId = 4,
                            PayeeId = 21000365,
                            USDAmount = 353m
                        },
                        new
                        {
                            ItemId = 15,
                            Amount = 234m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 5,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4107),
                            Description = "	Office supplies, Sept 2019	",
                            ExpenseClaimId = 2,
                            PayeeId = 21000173,
                            USDAmount = 234m
                        },
                        new
                        {
                            ItemId = 16,
                            Amount = 3454m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 1,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4139),
                            Description = "	Website and software expenses, Nov 2021	",
                            ExpenseClaimId = 5,
                            PayeeId = 21000546,
                            USDAmount = 4179m
                        },
                        new
                        {
                            ItemId = 17,
                            Amount = 650000m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 2,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4173),
                            Description = "	Furniture, March 2020	",
                            ExpenseClaimId = 1,
                            PayeeId = 21000812,
                            USDAmount = 579m
                        },
                        new
                        {
                            ItemId = 18,
                            Amount = 3497m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 3,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4210),
                            Description = "	Entertainment, Oct 2018	",
                            ExpenseClaimId = 3,
                            PayeeId = 21000319,
                            USDAmount = 2868m
                        },
                        new
                        {
                            ItemId = 19,
                            Amount = 59430m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 4,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4238),
                            Description = "	Office supplies, May 2021	",
                            ExpenseClaimId = 4,
                            PayeeId = 21000986,
                            USDAmount = 541m
                        },
                        new
                        {
                            ItemId = 20,
                            Amount = 10890m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 5,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4287),
                            Description = "	Advertising and marketing, Feb 2020	",
                            ExpenseClaimId = 2,
                            PayeeId = 21000365,
                            USDAmount = 10890m
                        },
                        new
                        {
                            ItemId = 21,
                            Amount = 1046m,
                            CategoryId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 1,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4308),
                            Description = "	Advertising and marketing, Feb 2020	",
                            ExpenseClaimId = 5,
                            PayeeId = 21000173,
                            USDAmount = 1266m
                        },
                        new
                        {
                            ItemId = 22,
                            Amount = 8000000m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 2,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4327),
                            Description = "	Website and software expenses, Nov 2021	",
                            ExpenseClaimId = 1,
                            PayeeId = 21000546,
                            USDAmount = 7120m
                        },
                        new
                        {
                            ItemId = 23,
                            Amount = 54986m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 3,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4346),
                            Description = "	Advertising and marketing, Feb 2020	",
                            ExpenseClaimId = 3,
                            PayeeId = 21000812,
                            USDAmount = 45089m
                        },
                        new
                        {
                            ItemId = 24,
                            Amount = 42300m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 4,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4365),
                            Description = "	Furniture, March 2020	",
                            ExpenseClaimId = 4,
                            PayeeId = 21000319,
                            USDAmount = 385m
                        },
                        new
                        {
                            ItemId = 25,
                            Amount = 3067m,
                            CategoryId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 5,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4384),
                            Description = "	Office supplies, Sept 2019	",
                            ExpenseClaimId = 2,
                            PayeeId = 21000986,
                            USDAmount = 3067m
                        },
                        new
                        {
                            ItemId = 26,
                            Amount = 3096m,
                            CategoryId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 1,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4402),
                            Description = "	Advertising and marketing, Feb 2020	",
                            ExpenseClaimId = 5,
                            PayeeId = 21000365,
                            USDAmount = 3746m
                        },
                        new
                        {
                            ItemId = 27,
                            Amount = 895320m,
                            CategoryId = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 2,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4421),
                            Description = "	Advertising and marketing, Feb 2020	",
                            ExpenseClaimId = 1,
                            PayeeId = 21000173,
                            USDAmount = 797m
                        },
                        new
                        {
                            ItemId = 28,
                            Amount = 578m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 3,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4441),
                            Description = "	Furniture, March 2020	",
                            ExpenseClaimId = 3,
                            PayeeId = 21000546,
                            USDAmount = 474m
                        },
                        new
                        {
                            ItemId = 29,
                            Amount = 100587m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 4,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4460),
                            Description = "	Furniture, March 2020	",
                            ExpenseClaimId = 4,
                            PayeeId = 21000812,
                            USDAmount = 915m
                        },
                        new
                        {
                            ItemId = 30,
                            Amount = 3480m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 5,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4479),
                            Description = "	Furniture, March 2020	",
                            ExpenseClaimId = 2,
                            PayeeId = 21000319,
                            USDAmount = 3480m
                        },
                        new
                        {
                            ItemId = 31,
                            Amount = 88659m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 4,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4498),
                            Description = "	Requesting claimsB	",
                            ExpenseClaimId = 5,
                            PayeeId = 21000986,
                            USDAmount = 807m
                        },
                        new
                        {
                            ItemId = 32,
                            Amount = 42387m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 1,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4516),
                            Description = "	bought a car	",
                            ExpenseClaimId = 1,
                            PayeeId = 21000365,
                            USDAmount = 51288m
                        },
                        new
                        {
                            ItemId = 33,
                            Amount = 3080000m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 2,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4535),
                            Description = "	Rental fee  Nov 2021	",
                            ExpenseClaimId = 3,
                            PayeeId = 21000173,
                            USDAmount = 2741m
                        },
                        new
                        {
                            ItemId = 34,
                            Amount = 3058m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 3,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4557),
                            Description = "	Rental fee  Nov 2021	",
                            ExpenseClaimId = 4,
                            PayeeId = 21000546,
                            USDAmount = 2508m
                        },
                        new
                        {
                            ItemId = 40,
                            Amount = 3480m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 5,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4576),
                            Description = "	Furniture, March 2020	",
                            ExpenseClaimId = 6,
                            PayeeId = 21000319,
                            USDAmount = 3480m
                        },
                        new
                        {
                            ItemId = 41,
                            Amount = 88659m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 4,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4620),
                            Description = "	Requesting claimsB	",
                            ExpenseClaimId = 6,
                            PayeeId = 21000986,
                            USDAmount = 807m
                        },
                        new
                        {
                            ItemId = 42,
                            Amount = 42387m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 1,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4809),
                            Description = "	bought a car	",
                            ExpenseClaimId = 6,
                            PayeeId = 21000365,
                            USDAmount = 51288m
                        },
                        new
                        {
                            ItemId = 43,
                            Amount = 3080000m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 2,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4831),
                            Description = "	Rental fee  Nov 2021	",
                            ExpenseClaimId = 7,
                            PayeeId = 21000173,
                            USDAmount = 2741m
                        },
                        new
                        {
                            ItemId = 44,
                            Amount = 3058m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 3,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4850),
                            Description = "	Rental fee  Nov 2021	",
                            ExpenseClaimId = 7,
                            PayeeId = 21000546,
                            USDAmount = 2508m
                        },
                        new
                        {
                            ItemId = 45,
                            Amount = 3480m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 5,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4868),
                            Description = "	Furniture, March 2020	",
                            ExpenseClaimId = 7,
                            PayeeId = 21000319,
                            USDAmount = 3480m
                        },
                        new
                        {
                            ItemId = 46,
                            Amount = 88659m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 4,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4888),
                            Description = "	Requesting claimsB	",
                            ExpenseClaimId = 7,
                            PayeeId = 21000986,
                            USDAmount = 807m
                        },
                        new
                        {
                            ItemId = 47,
                            Amount = 42387m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 1,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4908),
                            Description = "	bought a car	",
                            ExpenseClaimId = 8,
                            PayeeId = 21000365,
                            USDAmount = 51288m
                        },
                        new
                        {
                            ItemId = 48,
                            Amount = 3080000m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 2,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4927),
                            Description = "	Rental fee  Nov 2021	",
                            ExpenseClaimId = 8,
                            PayeeId = 21000173,
                            USDAmount = 2741m
                        },
                        new
                        {
                            ItemId = 49,
                            Amount = 3058m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 3,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4946),
                            Description = "	Rental fee  Nov 2021	",
                            ExpenseClaimId = 8,
                            PayeeId = 21000546,
                            USDAmount = 2508m
                        },
                        new
                        {
                            ItemId = 50,
                            Amount = 3480m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 5,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4966),
                            Description = "	Furniture, March 2020	",
                            ExpenseClaimId = 9,
                            PayeeId = 21000319,
                            USDAmount = 3480m
                        },
                        new
                        {
                            ItemId = 51,
                            Amount = 88659m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 4,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(4985),
                            Description = "	Requesting claimsB	",
                            ExpenseClaimId = 9,
                            PayeeId = 21000986,
                            USDAmount = 807m
                        },
                        new
                        {
                            ItemId = 52,
                            Amount = 42387m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 1,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(5005),
                            Description = "	bought a car	",
                            ExpenseClaimId = 9,
                            PayeeId = 21000365,
                            USDAmount = 51288m
                        },
                        new
                        {
                            ItemId = 53,
                            Amount = 3080000m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 2,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(5024),
                            Description = "	Rental fee  Nov 2021	",
                            ExpenseClaimId = 10,
                            PayeeId = 21000173,
                            USDAmount = 2741m
                        },
                        new
                        {
                            ItemId = 54,
                            Amount = 3058m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 3,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(5043),
                            Description = "	Rental fee  Nov 2021	",
                            ExpenseClaimId = 10,
                            PayeeId = 21000546,
                            USDAmount = 2508m
                        },
                        new
                        {
                            ItemId = 55,
                            Amount = 3480m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 5,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(5063),
                            Description = "	Furniture, March 2020	",
                            ExpenseClaimId = 11,
                            PayeeId = 21000319,
                            USDAmount = 3480m
                        },
                        new
                        {
                            ItemId = 56,
                            Amount = 88659m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 4,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(5082),
                            Description = "	Requesting claimsB	",
                            ExpenseClaimId = 12,
                            PayeeId = 21000986,
                            USDAmount = 807m
                        },
                        new
                        {
                            ItemId = 57,
                            Amount = 42387m,
                            CategoryId = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 1,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(5101),
                            Description = "	bought a car	",
                            ExpenseClaimId = 13,
                            PayeeId = 21000365,
                            USDAmount = 51288m
                        },
                        new
                        {
                            ItemId = 58,
                            Amount = 3080000m,
                            CategoryId = 5,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 2,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(5145),
                            Description = "	Rental fee  Nov 2021	",
                            ExpenseClaimId = 14,
                            PayeeId = 21000173,
                            USDAmount = 2741m
                        },
                        new
                        {
                            ItemId = 59,
                            Amount = 3058m,
                            CategoryId = 6,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrencyId = 3,
                            Date = new DateTime(2021, 11, 15, 22, 56, 33, 430, DateTimeKind.Local).AddTicks(5335),
                            Description = "	Rental fee  Nov 2021	",
                            ExpenseClaimId = 15,
                            PayeeId = 21000546,
                            USDAmount = 2508m
                        });
                });

            modelBuilder.Entity("KakaoExpenseClaim.ClaimManagement.Domain.Entities.Item", b =>
                {
                    b.HasOne("KakaoExpenseClaim.ClaimManagement.Domain.Entities.ExpenseClaim", "ExpenseClaim")
                        .WithMany("Items")
                        .HasForeignKey("ExpenseClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExpenseClaim");
                });

            modelBuilder.Entity("KakaoExpenseClaim.ClaimManagement.Domain.Entities.ExpenseClaim", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
